/* index.js — Wreckers
   Wreckers คือคนที่ล่อเรือให้ชนโขดหินแล้วเก็บของจากซาก เป็นอาชีพจริงในประวัติศาสตร์
   ตอนนี้เป็นโครงเปล่า เลือกและกดเริ่มได้แล้ว แต่ยังรอกติกาจริง */

import { register } from '../../games.js';
import { init, onAction, tick } from './game.js';
import { render } from './ui.js';
import { EXTRA_CARDS } from './cards.js';
import { TURN_OPTIONS } from './board.js';
import { DUTCH_OPTIONS, dutchAllowed, DUTCH_NEEDS } from './rules.js';

register({
  id: 'wreckers',
  category: 'board',
  cover: 'assets/game/wreckers/cover.png',
  table: 'assets/game/wreckers/table.png',
  music: 'assets/music/wreckers.mp3',

  /* เสียงบรรยากาศวนต่อเนื่อง แยกหลอดจากเพลง
     นกนางนวลตั้งดังกว่าคลื่นเกือบเท่าตัว ไม่งั้นจะจมหายไปในเสียงคลื่น */
  ambience: [
    { src: 'assets/SFX/Ocean.mp3',  gain: 0.55 },
    { src: 'assets/SFX/Seagul.mp3', gain: 1.0 }
  ],
  minPlayers: 4,
  maxPlayers: 10,
  spectators: true,
  allowSpectatorChat: true,

  settings: [
    { key: 'turnSeconds', default: 0, options: TURN_OPTIONS },
    /* enabled กับ hint เป็นข้อมูลที่เกมประกาศเอง หน้าตั้งค่าแค่วาดตาม
       ปุ่มดัตช์กดได้เฉพาะจำนวนคนที่แบ่งฝั่งแล้วยังลงตัว */
    { key: 'dutch', default: 'auto', options: DUTCH_OPTIONS, hint: true,
      enabled: (value, count) => dutchAllowed(count, value) },
    { key: 'extraCards', type: 'cards', default: [], catalogue: EXTRA_CARDS }
  ],
  init, onAction, tick, render,

  i18n: {
    th: {
      'game.wreckers.name': 'Wreckers',
      'game.wreckers.desc': '4–10 คน · โจรสลัดแย่งสมบัติกันบนเรือที่กำลังจะจม ไว้ใจใครไม่ได้สักคน',
      'game.wreckers.extraCards': 'การ์ดพิเศษ (ยิ่งใส่เยอะ เกมยิ่งนาน)',
      'wreck.board': 'กระดาน',
      'game.wreckers.turnSeconds': 'เวลาต่อตา',
      'game.wreckers.turnSeconds.30': '30 วิ',
      'game.wreckers.turnSeconds.45': '45 วิ',
      'game.wreckers.turnSeconds.60': '60 วิ',
      'game.wreckers.turnSeconds.90': '90 วิ',
      'game.wreckers.turnSeconds.120': '120 วิ',
      'wreck.rolling': 'กำลังทอยหาคนเริ่ม',
      'wreck.starts': '{name} เริ่มก่อน',
      'wreck.yourTurn': 'ตาคุณ',
      'wreck.waitFor': 'รอ {name}',
      'wreck.left': 'เหลือ {n} วิ',
      'wreck.offline': '{name} หลุดอยู่ รออีกสักครู่',
      'wreck.act.toBoatL': 'ลงเรือเล็กซ้าย',
      'wreck.act.toBoatR': 'ลงเรือเล็กขวา',
      'wreck.act.forceEvent': 'บังคับให้เปิดการ์ด',
      'wreck.act.kickOff': 'ไล่ลงจากเรือ',
      'wreck.act.activate': 'Activate',
      'wreck.act.peek': 'Peek',
      'wreck.boatTaken': 'เรือเล็กลำนี้มีคนอยู่แล้ว',
      'wreck.pickMore': 'เลือกได้อีก 1 ใบ หรือกด Peek เลยก็ได้',
      'wreck.forcing': 'กำลังบังคับ {name} — เลือกการ์ด 2 ใบ',
      'wreck.cancel': 'ยกเลิก',
      'wreck.shiftHere': 'ย้ายกล่องนี้',
      'wreck.actions': 'สิ่งที่ทำได้',
      'wreck.eventDeck': 'การ์ดเหตุการณ์ในกอง',
      'wreck.voteDeck': 'ไพ่โหวตในกอง',
      'wreck.noRoleAction': 'ตำแหน่งนี้ไม่มี Action พิเศษ',
      'wreck.notWired': 'ปุ่มยังไม่ต่อกติกา ใส่ไว้ดูผังก่อน',
      'wreck.act.force': 'บังคับคนอื่นเปิด',
      'wreck.act.attack': 'สั่งโหวตโจมตี',
      'wreck.act.kick': 'ไล่ลงจากเรือ',
      'wreck.act.mutiny': 'สั่งโหวตก่อกบฏ',
      'wreck.act.shiftCargo': 'ย้ายกล่องบนเรือ',
      'wreck.act.islandVote': 'สั่งโหวตย้ายกล่องบนเกาะ',
      'wreck.yourHand': 'ไพ่ของคุณ',
      'wreck.players': 'ผู้เล่น',
      'wreck.events': 'การ์ดเหตุการณ์',
      'wreck.event': 'EVENT',
      'wreck.vote': 'VOTE',
      'wreck.noCards': 'ยังไม่มีไพ่',
      'wreck.voteSpent': 'ไพ่โหวตหมดถาวร — ร่วมโหวตไม่ได้อีกแล้ว',
      'wreck.sittingOut': 'การโหวตครั้งนี้ไม่นับคุณด้วย',
      'wreck.role.captain': 'กัปตัน',
      'wreck.role.mate': 'ต้นหน',
      'wreck.role.cabin': 'ลูกเรือ',
      'wreck.role.governor': 'ประธานเกาะ',
      'wreck.role.people': 'ชาวเกาะ',
      'wreck.role.rowboat': 'เรือเล็ก',
      'wreck.tapToMove': 'แตะวงว่างเพื่อย้ายตัวเอง',
      'wreck.watchingOnly': 'กำลังนั่งดู ขยับไม่ได้',
      'wreck.british': 'British',
      'wreck.france': 'France',
      'wreck.merchant': 'เรือสินค้า',
      'game.wreckers.dutch': 'จำนวนดัตช์',
      'game.wreckers.dutch.auto': 'ตามจำนวนคน',
      'game.wreckers.dutch.1': '1 คน',
      'game.wreckers.dutch.2': '2 คน',
      'game.wreckers.dutch.hint':
        'ตามจำนวนคน = คนคี่ได้ดัตช์ 1 คน คนคู่ไม่มีดัตช์ · เลือก 1 คนได้เมื่อมี 5, 7, 9 คน · เลือก 2 คนได้เมื่อมี 8, 10 คน',
      'game.wreckers.turnSeconds.0': 'ไม่จับเวลา',

      'wreck.nation.head': 'ประเทศของคุณ',
      'wreck.nation.you': 'คุณคือ {nation}',
      'wreck.nation.hide': 'อย่าให้ใครเห็นจอ',
      'wreck.nation.B.tag': 'บริติช',
      'wreck.nation.F.tag': 'ฝรั่งเศส',
      'wreck.nation.D.tag': 'ดัตช์',
      'wreck.nation.B.goal': 'ชนะเมื่อฝั่งบริติชมีกล่องมากที่สุด',
      'wreck.nation.F.goal': 'ชนะเมื่อฝั่งฝรั่งเศสมีกล่องมากที่สุด',
      'wreck.nation.D.goal': 'ชนะเมื่อสองฝั่งมีกล่องเท่ากัน',
      'wreck.offlineWait': 'รอ {n} วินาทีเผื่อคนที่หลุดกลับมา',
      'wreck.dev.pick': 'เลือกการ์ด',
      'wreck.dev.swap': 'เครื่องมือทดสอบ — เปลี่ยนการ์ดในช่อง {n}',
      'wreck.dev.find': 'พิมพ์ค้นชื่อการ์ด',
      'wreck.dev.none': 'ไม่พบการ์ดที่ตรงกับคำค้น',
      'wreck.peekLeft': 'แอบดูได้อีก {n} ใบ — เลือกอีกใบแล้วกด Peek',

      'wreck.scene.shoot': 'Call to Shoot',
      'wreck.scene.mutiny': 'Call to Mutiny',
      'wreck.scene.brawl': 'Call to Brawl',
      'wreck.scene.aim': 'Take the Prize',
      'wreck.scene.pickShipBig': 'Choose the Ship to Shoot',
      'wreck.scene.waiting': 'ยังไม่ส่งไพ่: {who}',
      'wreck.scene.allIn': 'ส่งครบทุกคนแล้ว',
      'wreck.scene.fromDeck': 'จากกองกลาง',
      'wreck.loading': 'กำลังโหลดภาพของกระดาน',
      'wreck.scene.peeked': '{name} แอบดูการ์ดช่อง {slots}',
      'wreck.scene.takeFrom': 'ขโมยกล่องจากฝั่งไหนของ{where}',
      'wreck.scene.keepOn': 'เก็บกล่องไว้ฝั่งไหนของ{where}',
      'wreck.scene.noBox': 'ไม่มีกล่อง',
      'wreck.scene.full': 'เต็มแล้ว',
      'wreck.scene.took': 'กัปตัน {name} ชิงกล่องสมบัติจาก{from} มาให้{side}',
      'wreck.scene.shuffling': 'สับไพ่ในหม้อ',
      'wreck.scene.hit': 'ยิงเข้าเป้า',
      'wreck.scene.miss': 'ยิงพลาด',
      'wreck.scene.waitAim': 'รอ {name} เลือกเป้า',
      'wreck.scene.pickShip': 'คลิกเรือที่จะยิง',
      'wreck.scene.pickSide': 'เก็บกล่องไว้ฝั่งไหน',
      'wreck.sym.C': 'ปืนใหญ่',
      'wreck.sym.F': 'ไฟ',
      'wreck.sym.W': 'น้ำ',
      'wreck.place.merchant': 'เรือสินค้า',
      'wreck.place.boatL': 'เรือเล็กลำซ้าย',
      'wreck.place.boatR': 'เรือเล็กลำขวา',
      'wreck.place.shipL': 'เรือลำซ้าย',
      'wreck.place.shipR': 'เรือลำขวา',
      'wreck.log.attackTook': 'ชิงกล่องจาก{target} เก็บไว้ฝั่ง {side}',
      'wreck.opened': '{name} เปิดการ์ด',
      'wreck.peeked': 'คุณแอบดูไว้ — คนอื่นยังเห็นเป็นไพ่คว่ำ',
      'wreck.log.devCard': 'เครื่องมือทดสอบ: เปลี่ยนการ์ดในช่อง {slot}',

      'wreck.plan.target': 'ยิงลำไหน',
      'wreck.plan.otherShip': 'เรืออีกลำ',
      'wreck.plan.take': 'ชิงจากฝั่ง',
      'wreck.plan.store': 'เก็บไว้ฝั่ง',
      'wreck.plan.move': 'ย้ายกล่อง',
      'wreck.plan.bToF': 'บริติช → ฝรั่งเศส',
      'wreck.plan.fToB': 'ฝรั่งเศส → บริติช',
      'wreck.plan.who': 'ไล่ใคร',
      'wreck.plan.confirm': 'ยืนยัน',
      'wreck.act.useCard': 'ใช้การ์ดกับผู้เล่นคนนี้',
      'wreck.act.playHeld': 'ใช้{card}',
      'wreck.card.pistol': 'ปืนพก',
      'wreck.card.blackspot': 'จุดดำ',
      'wreck.card.marque': 'หนังสือตราตั้ง',
      'wreck.card.fountain': 'น้ำพุอมตะ',
      'wreck.card.atlantis': 'แอตแลนติส',
      'wreck.card.eldorado': 'เอลโดราโด',
      'wreck.card.lyonesse': 'ลีอองเนส',
      'wreck.card.anthemoessa': 'อันเทโมเอสซา',
      'wreck.ask.map.player': 'เลือกคนที่จะยกแผนที่ให้ — ให้ตัวเองไม่ได้',
      'wreck.scene.saveAsk': 'จะใช้การ์ดใบนี้กันไว้ไหม ใช้แล้วการ์ดหายไป',
      'wreck.scene.saveYes': 'ใช้',
      'wreck.scene.saveNo': 'ไม่ใช้',
      'wreck.scene.saveWait': 'รอ {name} ตัดสินใจว่าจะใช้การ์ดหรือไม่',
      'wreck.scene.savedBy': '{name} ใช้{card} รอดจากการถูกทิ้งเกาะ',
      'wreck.scene.gaveMap': '{name} ยก{card}ให้ {who}',
      'wreck.log.saveYes': '{name} ใช้การ์ดกันไว้ ไม่โดนทิ้งเกาะ',
      'wreck.log.saveNo': '{name} ไม่ใช้การ์ด โดนทิ้งเกาะตามเดิม',
      'wreck.ask.any.player': 'เลือกผู้เล่น',
      'wreck.ask.any.ship': 'เลือกเรือ',
      'wreck.ask.pistol.player': 'เลือกคนที่จะยิง — บนกระดานหรือในรายชื่อก็ได้',
      'wreck.ask.marque.player': 'เลือกคนที่จะเชิญขึ้นเรือ — ตัวเองก็ได้',
      'wreck.ask.marque.ship': 'เลือกเรือที่จะให้เขาไปต่อท้ายแถว',
      'wreck.act.held': 'การ์ดในมือ',
      'wreck.cardWait': 'ใบนี้ใช้ได้เฉพาะในตาของตัวเอง',
      'wreck.cardNoRoom': 'ตอนนี้ใช้ใบนี้ไม่ได้ ไม่มีเป้าที่เลือกได้',
      'wreck.plan.card': 'การ์ด',
      'wreck.log.playHeld': '{name} หยิบการ์ดจากมือมาใช้',
      'wreck.log.queued': '{name} ใช้การ์ดแทรก ผลจะเกิดหลังจบตานี้',
      'wreck.log.gaveMap': '{name} ยกแผนที่ให้ {who}',
      'wreck.log.card.atlantis': '{name} แทรกเข้าไปยืนหลัง {who}',
      'wreck.scene.atlantis': '{name} แทรกเข้าไปยืนข้างหลัง {who}',
      'wreck.scene.atlantisSpill': '{name} แทรกหลัง {who} — {n} คนถูกล่นตกเรือ',
      'wreck.log.card.marque': '{name} ใช้หนังสือตราตั้งส่ง {who} ขึ้นเรือ',
      'wreck.scene.marque': '{name} ส่ง {who} ขึ้น{place}',
      'wreck.scene.pickShipWarp': 'เลือกเรือที่จะส่งขึ้นไป',
      'wreck.act.aimAt': 'เลือกลำที่จะยิง',
      'wreck.act.takeFrom': 'เลือกฝั่งที่จะขโมย',
      'wreck.act.storeAt': 'เลือกฝั่งที่จะเก็บ',
      'wreck.act.toBoat': 'ลงเรือเล็ก',
      'wreck.scene.mutinyWin': 'ก่อกบฏสำเร็จ กัปตันถูกปลด',
      'wreck.scene.mutinyFail': 'ก่อกบฏล้มเหลว กัปตันอยู่ต่อ',
      'wreck.scene.brawlDone': 'กล่องบนเกาะ บริติช {B} · ฝรั่งเศส {F}',
      'wreck.scene.kicked': 'กัปตัน {name} ไล่ {who} ลงจากเรือ',
      'wreck.scene.shifted': '{name} ย้ายกล่องจาก{from}ไป{to}',
      'wreck.log.card.pistol': '{name} ยิง {who} ด้วยปืนพก',
      'wreck.log.card.blackspot': '{name} เปิดเจอจุดดำ โดน Maroon',
      'wreck.log.card.albatross': '{name} เปิดเจอนกอัลบาทรอส นกเกาะติดตัวไว้',
      'wreck.log.birds': 'เรือลำนี้มีนกครบสองตัว ทั้งลำ {n} คนโดน Maroon',
      'wreck.card.albatross': 'นกอัลบาทรอส',
      'wreck.scene.birdsBig': 'ฝูงนกถล่มเรือ',
      'wreck.scene.birds': 'นกครบสองตัวบนเรือลำเดียว — ทั้งลำ {n} คนโดน Maroon',
      'wreck.token.bird': 'มีนกอัลบาทรอสเกาะติดตัว',
      'wreck.scene.shot': '{name} ยิง {who}',
      'wreck.scene.cardUp': 'เปิดการ์ด',
      'wreck.scene.pickTargetBig': 'เลือกเป้า',
      'wreck.scene.pickTargetMe': 'คลิกผู้เล่นที่จะยิง — บนกระดานหรือในรายชื่อก็ได้',
      'wreck.scene.pickTargetThem': 'รอ {name} เลือกว่าจะยิงใคร',

      'wreck.vote.open': 'กำลังโหวตอยู่',
      'wreck.vote.pick': 'เลือกไพ่หนึ่งใบส่งเข้าหม้อ',
      'wreck.vote.sent': 'ส่งไพ่แล้ว รอคนอื่น',
      'wreck.vote.elsewhere': 'โหวตนี้ไม่เกี่ยวกับที่ที่คุณยืนอยู่',
      'wreck.vote.waiting': 'รออีก {n} คน',
      'wreck.vote.calling.attack': '{name} สั่งโหวตโจมตี',
      'wreck.vote.calling.mutiny': '{name} สั่งโหวตก่อกบฏ',
      'wreck.vote.calling.islandVote': '{name} สั่งโหวตย้ายกล่องบนเกาะ',
      'wreck.vote.result.attack': 'ผลการโจมตี',
      'wreck.vote.result.mutiny': 'ผลการก่อกบฏ',
      'wreck.vote.result.islandVote': 'ผลการย้ายกล่อง',
      'wreck.over.done': 'จบเกมแล้ว',
      'wreck.over.score': 'บริติช {B} · ฝรั่งเศส {F}',
      'wreck.over.win.B': 'บริติชชนะ',
      'wreck.over.win.F': 'ฝรั่งเศสชนะ',
      'wreck.over.win.D': 'เท่ากัน ดัตช์ชนะ',
      'wreck.nation.B': 'บริติช',
      'wreck.nation.F': 'ฝรั่งเศส',
      'wreck.nation.D': 'ดัตช์',

      'wreck.log.cardLost': '{name} ไม่ได้เลือกเป้าทันเวลา ผลการ์ดหายไป',
      'wreck.log.activate': '{name} เปิดการ์ดเหตุการณ์',
      'wreck.log.peek': '{name} แอบดูการ์ดช่อง {at}',
      'wreck.log.peekOne': '{name} แอบดูไปหนึ่งใบ เหลืออีก {n}',
      'wreck.log.force': '{name} บังคับให้คนอื่นเปิดการ์ด',
      'wreck.log.toBoat': '{name} ลงเรือเล็ก{which} รอขึ้นฝั่งในตาถัดไป',
      'wreck.log.ashore': '{name} ขึ้นฝั่งแล้ว',
      'wreck.log.boatStuck': '{name} ขึ้นฝั่งไม่ได้ ที่นั่นเต็ม',
      'wreck.log.kick': '{name} ไล่ {who} ลงจากเรือ',
      'wreck.log.shift': '{name} ย้ายกล่องข้ามฝั่ง',
      'wreck.log.timeout': 'หมดเวลาของ {name} ข้ามตาไป',
      'wreck.log.call.attack': '{name} สั่งโหวตโจมตี',
      'wreck.log.call.mutiny': '{name} สั่งโหวตก่อกบฏ',
      'wreck.log.call.islandVote': '{name} สั่งโหวตย้ายกล่องบนเกาะ',
      'wreck.log.attackWin': 'โจมตีสำเร็จ ชิงกล่องมาได้หนึ่งใบ',
      'wreck.log.attackFail': 'โจมตีล้มเหลว',
      'wreck.log.attackNoRoom': 'โจมตีสำเร็จ แต่เรือเต็มแล้ว วางกล่องไม่ได้',
      'wreck.log.mutinyWin': 'ก่อกบฏสำเร็จ {who} เด้งลงเกาะ',
      'wreck.log.mutinyFail': 'ก่อกบฏล้มเหลว กัปตันอยู่ต่อ',
      'wreck.log.brawl': 'กล่องบนเกาะกลายเป็นบริติช {B} ฝรั่งเศส {F}',
      'wreck.back': 'กลับไปที่ห้อง'
    },
    en: {
      'game.wreckers.name': 'Wreckers',
      'game.wreckers.desc': '4–10 players · pirates tearing into the same haul on a sinking ship, and nobody can be trusted',
      'game.wreckers.extraCards': 'Extra cards (the more you add, the longer the game)',
      'wreck.board': 'Board',
      'game.wreckers.turnSeconds': 'Turn timer',
      'game.wreckers.turnSeconds.30': '30s',
      'game.wreckers.turnSeconds.45': '45s',
      'game.wreckers.turnSeconds.60': '60s',
      'game.wreckers.turnSeconds.90': '90s',
      'game.wreckers.turnSeconds.120': '120s',
      'wreck.rolling': 'Rolling for first turn',
      'wreck.starts': '{name} goes first',
      'wreck.yourTurn': 'Your turn',
      'wreck.waitFor': 'Waiting for {name}',
      'wreck.left': '{n}s left',
      'wreck.offline': '{name} is offline \u2014 holding the turn',
      'wreck.act.toBoatL': 'Left rowboat',
      'wreck.act.toBoatR': 'Right rowboat',
      'wreck.act.forceEvent': 'Force them to flip',
      'wreck.act.kickOff': 'Throw off the ship',
      'wreck.act.activate': 'Activate',
      'wreck.act.peek': 'Peek',
      'wreck.boatTaken': 'That rowboat is taken',
      'wreck.pickMore': 'Pick one more, or just Peek',
      'wreck.forcing': 'Forcing {name} \u2014 pick two cards',
      'wreck.cancel': 'Cancel',
      'wreck.shiftHere': 'Shift this box',
      'wreck.actions': 'Actions',
      'wreck.eventDeck': 'events left in deck',
      'wreck.voteDeck': 'vote cards in pile',
      'wreck.noRoleAction': 'No special action from this spot',
      'wreck.notWired': 'Buttons are layout only — rules not wired yet',
      'wreck.act.force': 'Force someone to flip',
      'wreck.act.attack': 'Call an attack vote',
      'wreck.act.kick': 'Throw someone off',
      'wreck.act.mutiny': 'Call a mutiny vote',
      'wreck.act.shiftCargo': 'Shift cargo on the ship',
      'wreck.act.islandVote': 'Call an island cargo vote',
      'wreck.yourHand': 'Your hand',
      'wreck.players': 'Players',
      'wreck.events': 'Event cards',
      'wreck.event': 'EVENT',
      'wreck.vote': 'VOTE',
      'wreck.noCards': 'No cards yet',
      'wreck.voteSpent': 'All vote cards lost \u2014 you can no longer vote',
      'wreck.sittingOut': 'this vote does not include you',
      'wreck.role.captain': 'Captain',
      'wreck.role.mate': 'First Mate',
      'wreck.role.cabin': 'Crew',
      'wreck.role.governor': 'President',
      'wreck.role.people': 'Islander',
      'wreck.role.rowboat': 'Rowboat',
      'wreck.tapToMove': 'Tap an empty circle to move',
      'wreck.watchingOnly': 'Watching — you cannot move',
      'wreck.british': 'British',
      'wreck.france': 'France',
      'wreck.merchant': 'Merchant',
      'game.wreckers.dutch': 'Dutch players',
      'game.wreckers.dutch.auto': 'By player count',
      'game.wreckers.dutch.1': '1',
      'game.wreckers.dutch.2': '2',
      'game.wreckers.dutch.hint':
        'By player count = 1 Dutch for odd, none for even \u00b7 pick 1 with 5, 7, 9 players \u00b7 pick 2 with 8, 10',
      'game.wreckers.turnSeconds.0': 'No timer',

      'wreck.nation.head': 'Your nation',
      'wreck.nation.you': 'You are {nation}',
      'wreck.nation.hide': 'Keep this off other screens',
      'wreck.nation.B.tag': 'British',
      'wreck.nation.F.tag': 'France',
      'wreck.nation.D.tag': 'Dutch',
      'wreck.nation.B.goal': 'Win when British hold the most boxes',
      'wreck.nation.F.goal': 'Win when France hold the most boxes',
      'wreck.nation.D.goal': 'Win when both sides hold the same',
      'wreck.offlineWait': 'waiting {n}s in case they reconnect',
      'wreck.dev.pick': 'Choose Event',
      'wreck.dev.swap': 'Test tool \u2014 replace slot {n}',
      'wreck.dev.find': 'Search a card name',
      'wreck.dev.none': 'No card matches',
      'wreck.peekLeft': '{n} peek left \u2014 pick another card and press Peek',

      'wreck.scene.shoot': 'Call to Shoot',
      'wreck.scene.mutiny': 'Call to Mutiny',
      'wreck.scene.brawl': 'Call to Brawl',
      'wreck.scene.aim': 'Take the Prize',
      'wreck.scene.pickShipBig': 'Choose the Ship to Shoot',
      'wreck.scene.waiting': 'still to vote: {who}',
      'wreck.scene.allIn': 'everyone has voted',
      'wreck.scene.fromDeck': 'from the pile',
      'wreck.loading': 'Loading the board',
      'wreck.scene.peeked': '{name} peeked at slot {slots}',
      'wreck.scene.takeFrom': 'Take a box from which side of {where}?',
      'wreck.scene.keepOn': 'Store it on which side of {where}?',
      'wreck.scene.noBox': 'no boxes',
      'wreck.scene.full': 'full',
      'wreck.scene.took': 'Captain {name} takes a box from {from} for {side}',
      'wreck.scene.shuffling': 'shuffling the pot',
      'wreck.scene.hit': 'The shot lands',
      'wreck.scene.miss': 'The shot misses',
      'wreck.scene.waitAim': 'waiting for {name} to aim',
      'wreck.scene.pickShip': 'Click the ship to fire on',
      'wreck.scene.pickSide': 'Which side keeps the box?',
      'wreck.sym.C': 'Cannon',
      'wreck.sym.F': 'Fire',
      'wreck.sym.W': 'Water',
      'wreck.place.merchant': 'the merchant ship',
      'wreck.place.boatL': 'the left rowboat',
      'wreck.place.boatR': 'the right rowboat',
      'wreck.place.shipL': 'the left ship',
      'wreck.place.shipR': 'the right ship',
      'wreck.log.attackTook': 'took a box from {target} onto the {side} side',
      'wreck.opened': '{name} flipped',
      'wreck.peeked': 'You peeked at this \u2014 everyone else still sees the back',
      'wreck.log.devCard': 'Test tool: slot {slot} replaced',

      'wreck.plan.target': 'Fire at',
      'wreck.plan.otherShip': 'The other ship',
      'wreck.plan.take': 'Take from',
      'wreck.plan.store': 'Store on',
      'wreck.plan.move': 'Move a box',
      'wreck.plan.bToF': 'British \u2192 France',
      'wreck.plan.fToB': 'France \u2192 British',
      'wreck.plan.who': 'Throw off',
      'wreck.plan.confirm': 'Confirm',
      'wreck.act.useCard': 'Use the card on this player',
      'wreck.act.playHeld': 'Play {card}',
      'wreck.card.pistol': 'Pistol',
      'wreck.card.blackspot': 'Black Spot',
      'wreck.card.marque': 'Letter of Marque',
      'wreck.card.fountain': 'Fountain of Youth',
      'wreck.card.atlantis': 'Atlantis',
      'wreck.card.eldorado': 'El Dorado',
      'wreck.card.lyonesse': 'Lyonesse',
      'wreck.card.anthemoessa': 'Anthemoessa',
      'wreck.ask.map.player': 'Choose who receives the map \u2014 not yourself',
      'wreck.scene.saveAsk': 'Use this card to save yourself? It is spent either way.',
      'wreck.scene.saveYes': 'Use it',
      'wreck.scene.saveNo': 'Keep it',
      'wreck.scene.saveWait': 'waiting for {name} to decide',
      'wreck.scene.savedBy': '{name} spends the {card} and escapes marooning',
      'wreck.scene.gaveMap': '{name} hands the {card} to {who}',
      'wreck.log.saveYes': '{name} spends a card and avoids marooning',
      'wreck.log.saveNo': '{name} declines and is marooned',
      'wreck.ask.any.player': 'Choose a player',
      'wreck.ask.any.ship': 'Choose a ship',
      'wreck.ask.pistol.player': 'Click the player to shoot \u2014 on the board or in the list',
      'wreck.ask.marque.player': 'Choose who to invite aboard \u2014 yourself is allowed',
      'wreck.ask.marque.ship': 'Choose the ship they join, at the back of the queue',
      'wreck.act.held': 'Cards in hand',
      'wreck.cardWait': 'This card can only be played on your own turn',
      'wreck.cardNoRoom': 'No valid target for this card right now',
      'wreck.plan.card': 'Card',
      'wreck.log.playHeld': '{name} plays a card from hand',
      'wreck.log.queued': '{name} plays a card \u2014 it resolves after this turn',
      'wreck.log.gaveMap': '{name} hands the map to {who}',
      'wreck.log.card.atlantis': '{name} cuts in behind {who}',
      'wreck.scene.atlantis': '{name} cuts in behind {who}',
      'wreck.scene.atlantisSpill': '{name} cuts in behind {who} \u2014 {n} pushed overboard',
      'wreck.log.card.marque': '{name} sends {who} aboard with the Letter of Marque',
      'wreck.scene.marque': '{name} sends {who} to {place}',
      'wreck.scene.pickShipWarp': 'Choose the ship to send them to',
      'wreck.act.aimAt': 'Choose the ship to fire on',
      'wreck.act.takeFrom': 'Choose the side to take from',
      'wreck.act.storeAt': 'Choose the side to store on',
      'wreck.act.toBoat': 'Board the rowboat',
      'wreck.scene.mutinyWin': 'The mutiny carries \u2014 the Captain falls',
      'wreck.scene.mutinyFail': 'The mutiny fails \u2014 the Captain stays',
      'wreck.scene.brawlDone': 'Island cargo \u2014 British {B} \u00b7 France {F}',
      'wreck.scene.kicked': 'Captain {name} throws {who} off the ship',
      'wreck.scene.shifted': '{name} moves a box from {from} to {to}',
      'wreck.log.card.pistol': '{name} shot {who} with the pistol',
      'wreck.log.card.blackspot': '{name} drew the Black Spot and is marooned',
      'wreck.log.card.albatross': 'A bird settles on {name}',
      'wreck.log.birds': 'Two birds aboard \u2014 all {n} of the crew are marooned',
      'wreck.card.albatross': 'Albatross',
      'wreck.scene.birdsBig': 'The Birds Descend',
      'wreck.scene.birds': 'Two birds on one ship \u2014 all {n} aboard are marooned',
      'wreck.token.bird': 'carrying an albatross',
      'wreck.scene.shot': '{name} shoots {who}',
      'wreck.scene.cardUp': 'Event revealed',
      'wreck.scene.pickTargetBig': 'Choose a Target',
      'wreck.scene.pickTargetMe': 'Click the player to shoot \u2014 on the board or in the list',
      'wreck.scene.pickTargetThem': 'waiting for {name} to choose a target',

      'wreck.vote.open': 'A vote is underway',
      'wreck.vote.pick': 'Pick one card for the pot',
      'wreck.vote.sent': 'Card sent \u2014 waiting for the others',
      'wreck.vote.elsewhere': 'This vote does not reach where you stand',
      'wreck.vote.waiting': 'waiting on {n}',
      'wreck.vote.calling.attack': '{name} calls an attack vote',
      'wreck.vote.calling.mutiny': '{name} calls a mutiny vote',
      'wreck.vote.calling.islandVote': '{name} calls an island cargo vote',
      'wreck.vote.result.attack': 'Attack result',
      'wreck.vote.result.mutiny': 'Mutiny result',
      'wreck.vote.result.islandVote': 'Cargo vote result',
      'wreck.over.done': 'Game over',
      'wreck.over.score': 'British {B} \u00b7 France {F}',
      'wreck.over.win.B': 'British win',
      'wreck.over.win.F': 'France win',
      'wreck.over.win.D': 'Level \u2014 the Dutch win',
      'wreck.nation.B': 'British',
      'wreck.nation.F': 'France',
      'wreck.nation.D': 'Dutch',

      'wreck.log.cardLost': '{name} ran out of time — the card had no effect',
      'wreck.log.activate': '{name} flipped an event card',
      'wreck.log.peek': '{name} peeked at slot {at}',
      'wreck.log.peekOne': '{name} peeked at one \u2014 {n} to go',
      'wreck.log.force': '{name} forced someone to flip',
      'wreck.log.toBoat': '{name} boarded{which}, going ashore next turn',
      'wreck.log.ashore': '{name} came ashore',
      'wreck.log.boatStuck': '{name} could not land \u2014 no room',
      'wreck.log.kick': '{name} threw {who} off the ship',
      'wreck.log.shift': '{name} shifted a box across',
      'wreck.log.timeout': '{name} ran out of time \u2014 turn skipped',
      'wreck.log.call.attack': '{name} calls an attack vote',
      'wreck.log.call.mutiny': '{name} calls a mutiny vote',
      'wreck.log.call.islandVote': '{name} calls an island cargo vote',
      'wreck.log.attackWin': 'The attack lands \u2014 one box taken',
      'wreck.log.attackFail': 'The attack fails',
      'wreck.log.attackNoRoom': 'The attack lands but the ship is full',
      'wreck.log.mutinyWin': 'The mutiny carries \u2014 {who} is marooned',
      'wreck.log.mutinyFail': 'The mutiny fails \u2014 the Captain stays',
      'wreck.log.brawl': 'Island cargo is now British {B}, France {F}',
      'wreck.back': 'Back to the room'
    }
  }
});
