/* index.js — Wreckers
   Wreckers คือคนที่ล่อเรือให้ชนโขดหินแล้วเก็บของจากซาก เป็นอาชีพจริงในประวัติศาสตร์
   ตอนนี้เป็นโครงเปล่า เลือกและกดเริ่มได้แล้ว แต่ยังรอกติกาจริง */

import { register } from '../../games.js';
import { init, onAction, tick } from './game.js';
import { render } from './ui.js';
import { EXTRA_CARDS } from './cards.js';
import { TURN_OPTIONS } from './board.js';
import { DUTCH_OPTIONS, dutchAllowed, DUTCH_NEEDS } from './rules.js';

register({
  id: 'wreckers',
  category: 'board',
  cover: 'assets/game/wreckers/cover.png',
  table: 'assets/game/wreckers/table.png',
  music: 'assets/music/wreckers.mp3',

  /* เสียงบรรยากาศวนต่อเนื่อง แยกหลอดจากเพลง
     นกนางนวลตั้งดังกว่าคลื่นเกือบเท่าตัว ไม่งั้นจะจมหายไปในเสียงคลื่น */
  ambience: [
    { src: 'assets/SFX/Ocean.mp3',  gain: 0.55 },
    { src: 'assets/SFX/Seagul.mp3', gain: 1.0 }
  ],
  minPlayers: 4,
  maxPlayers: 10,
  spectators: true,
  allowSpectatorChat: true,

  settings: [
    { key: 'turnSeconds', default: 60, options: TURN_OPTIONS },
    /* enabled กับ hint เป็นข้อมูลที่เกมประกาศเอง หน้าตั้งค่าแค่วาดตาม
       ปุ่มดัตช์กดได้เฉพาะจำนวนคนที่แบ่งฝั่งแล้วยังลงตัว */
    { key: 'dutch', default: 'auto', options: DUTCH_OPTIONS, hint: true,
      enabled: (value, count) => dutchAllowed(count, value) },
    { key: 'extraCards', type: 'cards', default: [], catalogue: EXTRA_CARDS }
  ],
  init, onAction, tick, render,

  i18n: {
    th: {
      'game.wreckers.name': 'Wreckers',
      'game.wreckers.desc': '4–10 คน · โจรสลัดแย่งสมบัติกันบนเรือที่กำลังจะจม ไว้ใจใครไม่ได้สักคน',
      'game.wreckers.extraCards': 'การ์ดพิเศษ (ยิ่งใส่เยอะ เกมยิ่งนาน)',
      'wreck.board': 'กระดาน',
      'game.wreckers.turnSeconds': 'เวลาต่อตา',
      'game.wreckers.turnSeconds.30': '30 วิ',
      'game.wreckers.turnSeconds.45': '45 วิ',
      'game.wreckers.turnSeconds.60': '60 วิ',
      'game.wreckers.turnSeconds.90': '90 วิ',
      'game.wreckers.turnSeconds.120': '120 วิ',
      'wreck.rolling': 'กำลังทอยหาคนเริ่ม',
      'wreck.starts': '{name} เริ่มก่อน',
      'wreck.yourTurn': 'ตาคุณ',
      'wreck.waitFor': 'รอ {name}',
      'wreck.left': 'เหลือ {n} วิ',
      'wreck.offline': '{name} หลุดอยู่ รออีกสักครู่',
      'wreck.act.toBoat': 'ลงเรือเล็ก',
      'wreck.act.toBoatL': 'ลงเรือเล็กซ้าย',
      'wreck.act.toBoatR': 'ลงเรือเล็กขวา',
      'wreck.act.forceEvent': 'บังคับให้เปิดการ์ด',
      'wreck.act.kickOff': 'ไล่ลงจากเรือ',
      'wreck.act.activate': 'Activate',
      'wreck.act.peek': 'Peek',
      'wreck.boatTaken': 'เรือเล็กลำนี้มีคนอยู่แล้ว',
      'wreck.pickMore': 'เลือกได้อีก 1 ใบ หรือกด Peek เลยก็ได้',
      'wreck.forcing': 'กำลังบังคับ {name} — เลือกการ์ด 2 ใบ',
      'wreck.cancel': 'ยกเลิก',
      'wreck.shiftHere': 'ย้ายกล่องนี้',
      'wreck.actions': 'สิ่งที่ทำได้',
      'wreck.eventDeck': 'การ์ดเหตุการณ์ในกอง',
      'wreck.voteDeck': 'ไพ่โหวตในกอง',
      'wreck.noRoleAction': 'ตำแหน่งนี้ไม่มี Action พิเศษ',
      'wreck.notWired': 'ปุ่มยังไม่ต่อกติกา ใส่ไว้ดูผังก่อน',
      'wreck.act.force': 'บังคับคนอื่นเปิด',
      'wreck.act.attack': 'สั่งโหวตโจมตี',
      'wreck.act.kick': 'ไล่ลงจากเรือ',
      'wreck.act.mutiny': 'สั่งโหวตก่อกบฏ',
      'wreck.act.shiftCargo': 'ย้ายกล่องบนเรือ',
      'wreck.act.islandVote': 'สั่งโหวตย้ายกล่องบนเกาะ',
      'wreck.yourHand': 'ไพ่ของคุณ',
      'wreck.players': 'ผู้เล่น',
      'wreck.events': 'การ์ดเหตุการณ์',
      'wreck.event': 'EVENT',
      'wreck.vote': 'VOTE',
      'wreck.noCards': 'ยังไม่มีไพ่',
      'wreck.role.captain': 'กัปตัน',
      'wreck.role.mate': 'ต้นหน',
      'wreck.role.cabin': 'ลูกเรือ',
      'wreck.role.governor': 'ประธานเกาะ',
      'wreck.role.people': 'ชาวเกาะ',
      'wreck.role.rowboat': 'เรือเล็ก',
      'wreck.tapToMove': 'แตะวงว่างเพื่อย้ายตัวเอง',
      'wreck.watchingOnly': 'กำลังนั่งดู ขยับไม่ได้',
      'wreck.british': 'British',
      'wreck.france': 'France',
      'wreck.merchant': 'เรือสินค้า',
      'game.wreckers.dutch': 'จำนวนดัตช์',
      'game.wreckers.dutch.auto': 'ตามจำนวนคน',
      'game.wreckers.dutch.1': '1 คน',
      'game.wreckers.dutch.2': '2 คน',
      'game.wreckers.dutch.hint':
        'ตามจำนวนคน = คนคี่ได้ดัตช์ 1 คน คนคู่ได้ 2 คน · เลือก 1 คนได้เมื่อมี 5, 7, 9 คน · เลือก 2 คนได้เมื่อมี 8, 10 คน',
      'game.wreckers.turnSeconds.0': 'ไม่จับเวลา',

      'wreck.nation.head': 'ประเทศของคุณ',
      'wreck.nation.you': 'คุณคือ {nation}',
      'wreck.nation.hide': 'อย่าให้ใครเห็นจอ',
      'wreck.nation.B.tag': 'บริติช',
      'wreck.nation.F.tag': 'ฝรั่งเศส',
      'wreck.nation.D.tag': 'ดัตช์',
      'wreck.nation.B.goal': 'ชนะเมื่อฝั่งบริติชมีกล่องมากที่สุด',
      'wreck.nation.F.goal': 'ชนะเมื่อฝั่งฝรั่งเศสมีกล่องมากที่สุด',
      'wreck.nation.D.goal': 'ชนะเมื่อสองฝั่งมีกล่องเท่ากัน',
      'wreck.offlineWait': 'รอ {n} วินาทีเผื่อคนที่หลุดกลับมา',
      'wreck.dev.swap': 'เครื่องมือทดสอบ — เปลี่ยนการ์ดในช่อง {n}',
      'wreck.dev.find': 'พิมพ์ค้นชื่อการ์ด',
      'wreck.dev.none': 'ไม่พบการ์ดที่ตรงกับคำค้น',
      'wreck.peekLeft': 'แอบดูได้อีก {n} ใบ — เลือกอีกใบแล้วกด Peek',
      'wreck.opened': '{name} เปิดการ์ด',
      'wreck.peeked': 'คุณแอบดูไว้ — คนอื่นยังเห็นเป็นไพ่คว่ำ',
      'wreck.log.devCard': 'เครื่องมือทดสอบ: เปลี่ยนการ์ดในช่อง {slot}',

      'wreck.plan.target': 'ยิงลำไหน',
      'wreck.plan.otherShip': 'เรืออีกลำ',
      'wreck.plan.take': 'ชิงจากฝั่ง',
      'wreck.plan.store': 'เก็บไว้ฝั่ง',
      'wreck.plan.move': 'ย้ายกล่อง',
      'wreck.plan.bToF': 'บริติช → ฝรั่งเศส',
      'wreck.plan.fToB': 'ฝรั่งเศส → บริติช',
      'wreck.plan.who': 'ไล่ใคร',
      'wreck.plan.confirm': 'ยืนยัน',

      'wreck.vote.open': 'กำลังโหวตอยู่',
      'wreck.vote.pick': 'เลือกไพ่หนึ่งใบส่งเข้าหม้อ',
      'wreck.vote.sent': 'ส่งไพ่แล้ว รอคนอื่น',
      'wreck.vote.elsewhere': 'โหวตนี้ไม่เกี่ยวกับที่ที่คุณยืนอยู่',
      'wreck.vote.waiting': 'รออีก {n} คน',
      'wreck.vote.calling.attack': '{name} สั่งโหวตโจมตี',
      'wreck.vote.calling.mutiny': '{name} สั่งโหวตก่อกบฏ',
      'wreck.vote.calling.islandVote': '{name} สั่งโหวตย้ายกล่องบนเกาะ',
      'wreck.vote.result.attack': 'ผลการโจมตี',
      'wreck.vote.result.mutiny': 'ผลการก่อกบฏ',
      'wreck.vote.result.islandVote': 'ผลการย้ายกล่อง',
      'wreck.over.done': 'จบเกมแล้ว',
      'wreck.over.score': 'บริติช {B} · ฝรั่งเศส {F}',
      'wreck.over.win.B': 'บริติชชนะ',
      'wreck.over.win.F': 'ฝรั่งเศสชนะ',
      'wreck.over.win.D': 'เท่ากัน ดัตช์ชนะ',
      'wreck.nation.B': 'บริติช',
      'wreck.nation.F': 'ฝรั่งเศส',
      'wreck.nation.D': 'ดัตช์',

      'wreck.log.activate': '{name} เปิดการ์ดเหตุการณ์',
      'wreck.log.peek': '{name} แอบดูการ์ด {n} ใบ',
      'wreck.log.peekOne': '{name} แอบดูไปหนึ่งใบ เหลืออีก {n}',
      'wreck.log.force': '{name} บังคับให้คนอื่นเปิดการ์ด',
      'wreck.log.toBoat': '{name} ลงเรือเล็ก',
      'wreck.log.ashore': '{name} ขึ้นฝั่งแล้ว',
      'wreck.log.boatStuck': '{name} ขึ้นฝั่งไม่ได้ ที่นั่นเต็ม',
      'wreck.log.kick': '{name} ไล่ {who} ลงจากเรือ',
      'wreck.log.shift': '{name} ย้ายกล่องข้ามฝั่ง',
      'wreck.log.timeout': 'หมดเวลาของ {name} ข้ามตาไป',
      'wreck.log.call.attack': '{name} สั่งโหวตโจมตี',
      'wreck.log.call.mutiny': '{name} สั่งโหวตก่อกบฏ',
      'wreck.log.call.islandVote': '{name} สั่งโหวตย้ายกล่องบนเกาะ',
      'wreck.log.attackWin': 'โจมตีสำเร็จ ชิงกล่องมาได้หนึ่งใบ',
      'wreck.log.attackFail': 'โจมตีล้มเหลว',
      'wreck.log.attackNoRoom': 'โจมตีสำเร็จ แต่เรือเต็มแล้ว วางกล่องไม่ได้',
      'wreck.log.mutinyWin': 'ก่อกบฏสำเร็จ {who} เด้งลงเกาะ',
      'wreck.log.mutinyFail': 'ก่อกบฏล้มเหลว กัปตันอยู่ต่อ',
      'wreck.log.brawl': 'กล่องบนเกาะกลายเป็นบริติช {B} ฝรั่งเศส {F}',
      'wreck.back': 'กลับไปที่ห้อง'
    },
    en: {
      'game.wreckers.name': 'Wreckers',
      'game.wreckers.desc': '4–10 players · pirates tearing into the same haul on a sinking ship, and nobody can be trusted',
      'game.wreckers.extraCards': 'Extra cards (the more you add, the longer the game)',
      'wreck.board': 'Board',
      'game.wreckers.turnSeconds': 'Turn timer',
      'game.wreckers.turnSeconds.30': '30s',
      'game.wreckers.turnSeconds.45': '45s',
      'game.wreckers.turnSeconds.60': '60s',
      'game.wreckers.turnSeconds.90': '90s',
      'game.wreckers.turnSeconds.120': '120s',
      'wreck.rolling': 'Rolling for first turn',
      'wreck.starts': '{name} goes first',
      'wreck.yourTurn': 'Your turn',
      'wreck.waitFor': 'Waiting for {name}',
      'wreck.left': '{n}s left',
      'wreck.offline': '{name} is offline \u2014 holding the turn',
      'wreck.act.toBoat': 'Board the rowboat',
      'wreck.act.toBoatL': 'Left rowboat',
      'wreck.act.toBoatR': 'Right rowboat',
      'wreck.act.forceEvent': 'Force them to flip',
      'wreck.act.kickOff': 'Throw off the ship',
      'wreck.act.activate': 'Activate',
      'wreck.act.peek': 'Peek',
      'wreck.boatTaken': 'That rowboat is taken',
      'wreck.pickMore': 'Pick one more, or just Peek',
      'wreck.forcing': 'Forcing {name} \u2014 pick two cards',
      'wreck.cancel': 'Cancel',
      'wreck.shiftHere': 'Shift this box',
      'wreck.actions': 'Actions',
      'wreck.eventDeck': 'events left in deck',
      'wreck.voteDeck': 'vote cards in pile',
      'wreck.noRoleAction': 'No special action from this spot',
      'wreck.notWired': 'Buttons are layout only — rules not wired yet',
      'wreck.act.force': 'Force someone to flip',
      'wreck.act.attack': 'Call an attack vote',
      'wreck.act.kick': 'Throw someone off',
      'wreck.act.mutiny': 'Call a mutiny vote',
      'wreck.act.shiftCargo': 'Shift cargo on the ship',
      'wreck.act.islandVote': 'Call an island cargo vote',
      'wreck.yourHand': 'Your hand',
      'wreck.players': 'Players',
      'wreck.events': 'Event cards',
      'wreck.event': 'EVENT',
      'wreck.vote': 'VOTE',
      'wreck.noCards': 'No cards yet',
      'wreck.role.captain': 'Captain',
      'wreck.role.mate': 'First Mate',
      'wreck.role.cabin': 'Crew',
      'wreck.role.governor': 'President',
      'wreck.role.people': 'Islander',
      'wreck.role.rowboat': 'Rowboat',
      'wreck.tapToMove': 'Tap an empty circle to move',
      'wreck.watchingOnly': 'Watching — you cannot move',
      'wreck.british': 'British',
      'wreck.france': 'France',
      'wreck.merchant': 'Merchant',
      'game.wreckers.dutch': 'Dutch players',
      'game.wreckers.dutch.auto': 'By player count',
      'game.wreckers.dutch.1': '1',
      'game.wreckers.dutch.2': '2',
      'game.wreckers.dutch.hint':
        'By player count = 1 Dutch for odd, 2 for even \u00b7 pick 1 with 5, 7, 9 players \u00b7 pick 2 with 8, 10',
      'game.wreckers.turnSeconds.0': 'No timer',

      'wreck.nation.head': 'Your nation',
      'wreck.nation.you': 'You are {nation}',
      'wreck.nation.hide': 'Keep this off other screens',
      'wreck.nation.B.tag': 'British',
      'wreck.nation.F.tag': 'France',
      'wreck.nation.D.tag': 'Dutch',
      'wreck.nation.B.goal': 'Win when British hold the most boxes',
      'wreck.nation.F.goal': 'Win when France hold the most boxes',
      'wreck.nation.D.goal': 'Win when both sides hold the same',
      'wreck.offlineWait': 'waiting {n}s in case they reconnect',
      'wreck.dev.swap': 'Test tool \u2014 replace slot {n}',
      'wreck.dev.find': 'Search a card name',
      'wreck.dev.none': 'No card matches',
      'wreck.peekLeft': '{n} peek left \u2014 pick another card and press Peek',
      'wreck.opened': '{name} flipped',
      'wreck.peeked': 'You peeked at this \u2014 everyone else still sees the back',
      'wreck.log.devCard': 'Test tool: slot {slot} replaced',

      'wreck.plan.target': 'Fire at',
      'wreck.plan.otherShip': 'The other ship',
      'wreck.plan.take': 'Take from',
      'wreck.plan.store': 'Store on',
      'wreck.plan.move': 'Move a box',
      'wreck.plan.bToF': 'British \u2192 France',
      'wreck.plan.fToB': 'France \u2192 British',
      'wreck.plan.who': 'Throw off',
      'wreck.plan.confirm': 'Confirm',

      'wreck.vote.open': 'A vote is underway',
      'wreck.vote.pick': 'Pick one card for the pot',
      'wreck.vote.sent': 'Card sent \u2014 waiting for the others',
      'wreck.vote.elsewhere': 'This vote does not reach where you stand',
      'wreck.vote.waiting': 'waiting on {n}',
      'wreck.vote.calling.attack': '{name} calls an attack vote',
      'wreck.vote.calling.mutiny': '{name} calls a mutiny vote',
      'wreck.vote.calling.islandVote': '{name} calls an island cargo vote',
      'wreck.vote.result.attack': 'Attack result',
      'wreck.vote.result.mutiny': 'Mutiny result',
      'wreck.vote.result.islandVote': 'Cargo vote result',
      'wreck.over.done': 'Game over',
      'wreck.over.score': 'British {B} \u00b7 France {F}',
      'wreck.over.win.B': 'British win',
      'wreck.over.win.F': 'France win',
      'wreck.over.win.D': 'Level \u2014 the Dutch win',
      'wreck.nation.B': 'British',
      'wreck.nation.F': 'France',
      'wreck.nation.D': 'Dutch',

      'wreck.log.activate': '{name} flipped an event card',
      'wreck.log.peek': '{name} peeked at {n} card(s)',
      'wreck.log.peekOne': '{name} peeked at one \u2014 {n} to go',
      'wreck.log.force': '{name} forced someone to flip',
      'wreck.log.toBoat': '{name} boarded a rowboat',
      'wreck.log.ashore': '{name} came ashore',
      'wreck.log.boatStuck': '{name} could not land \u2014 no room',
      'wreck.log.kick': '{name} threw {who} off the ship',
      'wreck.log.shift': '{name} shifted a box across',
      'wreck.log.timeout': '{name} ran out of time \u2014 turn skipped',
      'wreck.log.call.attack': '{name} calls an attack vote',
      'wreck.log.call.mutiny': '{name} calls a mutiny vote',
      'wreck.log.call.islandVote': '{name} calls an island cargo vote',
      'wreck.log.attackWin': 'The attack lands \u2014 one box taken',
      'wreck.log.attackFail': 'The attack fails',
      'wreck.log.attackNoRoom': 'The attack lands but the ship is full',
      'wreck.log.mutinyWin': 'The mutiny carries \u2014 {who} is marooned',
      'wreck.log.mutinyFail': 'The mutiny fails \u2014 the Captain stays',
      'wreck.log.brawl': 'Island cargo is now British {B}, France {F}',
      'wreck.back': 'Back to the room'
    }
  }
});
