/* index.js — Who the fuq are you
   เกมทายลามะแนว social deduction + bluff (แกเป็นใคร)
   10 ลามะ · จุดเด่น 9 ข้อ · การ์ด Event 40 ใบ · 4–10 คน

   สถานะ: โครงเดินได้ — แจกลามะ ประกาศตัว เปิดการ์ด (โชว์ชื่อ) ทายจริง จบเกมได้
   ผลของการ์ด 40 ใบยังไม่ต่อ ตั้งใจทำทีละใบทีหลัง */

import { register } from '../../games.js';
import { init, onAction, tick } from './game.js';
import { render } from './ui.js';
import { WTF_GUIDE } from './guide.js';

const TALK_OPTIONS = [0, 60, 120, 180];       /* เวลาเฟสเผือก (วินาที) · 0 = ไม่จับเวลา */
const TURN_OPTIONS = [0, 30, 45, 60, 90];      /* เวลาต่อตาในเฟสทาย */

register({
  id: 'whothefuq',
  category: 'board',
  cover: 'assets/game/whothefuq/cover.png',
  minPlayers: 4,
  maxPlayers: 10,
  spectators: true,
  /* ข้อมูลลับเยอะ คนที่ออกไปแล้วรู้ความลับ — ปิดแชตคนดูกันหลุดข้อมูล */
  allowSpectatorChat: false,

  settings: [
    { key: 'talkSeconds', default: 120, options: TALK_OPTIONS },
    { key: 'turnSeconds', default: 60,  options: TURN_OPTIONS }
  ],

  init, onAction, tick, render,
  guide: WTF_GUIDE,

  i18n: {
    th: {
      'game.whothefuq.name': 'Who the fuq are you',
      'game.whothefuq.desc': '4–10 คน · เกมทายลามะแนวสืบสวน+บลัฟ ทุกคนถือลามะลับ ค่อย ๆ สืบจุดเด่นแล้วทายให้คนอื่นออก คนสุดท้ายที่ไม่มีใครทายถูกเป็นผู้ชนะ',

      'game.whothefuq.talkSeconds': 'เวลาเฟสเผือก',
      'game.whothefuq.talkSeconds.0': 'ไม่จับเวลา',
      'game.whothefuq.talkSeconds.60': '1 นาที',
      'game.whothefuq.talkSeconds.120': '2 นาที',
      'game.whothefuq.talkSeconds.180': '3 นาที',
      'game.whothefuq.turnSeconds': 'เวลาต่อตา (ทาย)',
      'game.whothefuq.turnSeconds.0': 'ไม่จับเวลา',
      'game.whothefuq.turnSeconds.30': '30 วิ',
      'game.whothefuq.turnSeconds.45': '45 วิ',
      'game.whothefuq.turnSeconds.60': '60 วิ',
      'game.whothefuq.turnSeconds.90': '90 วิ',

      'wtf.phase.announce': 'ประกาศตัว',
      'wtf.phase.event': 'ดวงลิขิต',
      'wtf.phase.talk': 'เผือกไทม์',
      'wtf.phase.challenge': 'แกเป็นใคร',
      'wtf.phase.over': 'จบเกม',
      'wtf.roundN': 'รอบที่ {n}',
      'wtf.secLeft': 'เหลือ {n} วิ',
      'wtf.youOut': 'คุณออกจากเกมแล้ว',
      'wtf.watching': 'กำลังนั่งดู',
      'wtf.secretHint': 'ลามะลับของคุณ — อย่าให้ใครเห็นจอ',
      'wtf.yourTraits': 'จุดเด่นของคุณ',
      'wtf.advance': 'ไปเฟสถัดไป',
      'wtf.hostNote': 'โฮสต์คุมจังหวะเฟสในโครงนี้',
      'wtf.youWin': 'คุณชนะ',
      'wtf.winnerIs': '{name} ชนะ',
      'wtf.again': 'เล่นอีกครั้ง',
      'wtf.lobby': 'กลับไปห้อง',
      'wtf.sayPh': 'พูดถึงลามะตัวเอง 1 ประโยค (โกหกได้)',
      'wtf.say': 'ประกาศ',
      'wtf.saidAlready': 'คุณประกาศไปแล้ว รอคนอื่น',
      'wtf.announceHelp': 'ทุกคนพูดถึงลามะตัวเอง 1 ประโยค จริงหรือบลัฟก็ได้',
      'wtf.announcedN': 'ประกาศแล้ว {n}/{of}',
      'wtf.flip': 'เปิดการ์ด',
      'wtf.waitFlip': 'รอคนเปิด',
      'wtf.notWired': 'ผลยังไม่ต่อกติกา',
      'wtf.talkHelp': 'ช่วงเผือก: ถาม แลกข้อมูล จับพันธมิตร โยนข้อมูลลวง',
      'wtf.yourHand': 'การ์ดในมือ',
      'wtf.noCards': 'ยังไม่มีการ์ดในมือ',
      'wtf.waitTurn': 'รอ {name} ตัดสินใจ',
      'wtf.challengeDone': 'ทุกคนตัดสินครบแล้ว รอโฮสต์ไปต่อ',
      'wtf.yourChallenge': 'ตาคุณ — จะทายใครเป็นลามะอะไร',
      'wtf.doChallenge': 'แกเป็นใคร',
      'wtf.skip': 'ข้าม',
      'wtf.players': 'ผู้เล่น',
      'wtf.tag.turn': 'ตานี้',
      'wtf.tag.flip': 'เปิดการ์ด',
      'wtf.tag.out': 'ออกแล้ว',
      'wtf.infoTable': 'ข้อมูลลามะ (10×9)',

      'wtf.log.announced': '{name} ประกาศ: {text}',
      'wtf.log.eventPhase': 'เข้าเฟสเปิดการ์ด รอบที่ {round}',
      'wtf.log.talkPhase': 'เข้าเฟสเผือก',
      'wtf.log.challengePhase': 'เข้าเฟสแกเป็นใคร',
      'wtf.log.held': '{name} เก็บการ์ดขึ้นมือ',
      'wtf.log.flipped': '{name} เปิดการ์ด',
      'wtf.log.hit': '{a} ทาย {b} ถูก — {b} ออกจากเกม',
      'wtf.log.miss': '{a} ทาย {b} พลาด',
      'wtf.log.skipped': '{name} ข้าม',
      'wtf.log.roundEnd': 'จบรอบที่ {round}',
      'wtf.log.played': '{name} ใช้การ์ด {card}',
      'wtf.log.missFree': '{a} ทาย {b} พลาด (ทายฟรี ไม่เสียโทษ)',
      'wtf.log.guessBackHit': '{a} ทายกลับ {b} ถูก — ออกทั้งคู่',
      'wtf.log.devFlip': '[dev] เสกการ์ด {card}',
      'wtf.pending.wait': 'กำลังรอ',
      'wtf.pending.who': 'รอ {who} เลือก',
      'wtf.confirm': 'ยืนยัน',
      'wtf.prompt.pickOwnTrait': 'เลือกจุดเด่นของตัวเอง 1 ข้อเพื่อเปิด (ต้องเป็นข้อที่มีจริง)',
      'wtf.prompt.pickAnyTrait': 'เลือกจุดเด่น 1 ข้อ',
      'wtf.prompt.pickTwo': 'เลือกจุดเด่น 2 ข้อ',
      'wtf.prompt.pickTarget': 'เลือกเป้าหมาย',
      'wtf.prompt.pickTargetTrait': 'เลือกเป้าหมายและจุดเด่น',
      'wtf.prompt.pickNeighbor': 'เลือกคนข้างๆ',
      'wtf.prompt.pickOut': 'เลือกคนที่ออกไปแล้ว',
      'wtf.prompt.bestie': 'เลือกคนข้างๆ และจุดเด่นที่จะบอก (โกหกได้)',
      'wtf.prompt.vote': 'โหวตเลือก 1 คน',
      'wtf.prompt.freeGuess': 'ทายเลย เลือกคนและลามะ',
      'wtf.prompt.duel': 'ทายลามะของอีกฝ่าย',
      'wtf.prompt.guessBack': 'ทายกลับ — ลามะของคนที่ทายคุณ',
      'wtf.seen.title': 'ข้อมูลที่คุณรู้คนเดียว',
      'wtf.seen.missing': 'ลามะที่ถูกถอด: {llama}',
      'wtf.seen.trait': '{name} มีจุดเด่น: {trait}',
      'wtf.seen.hasYes': '{name} มี {trait}',
      'wtf.seen.hasNo': '{name} ไม่มี {trait}',
      'wtf.seen.scan': '{name} มีจุดเด่น: {traits}',
      'wtf.seen.claim': '{name} อ้างว่ามีจุดเด่น: {trait}',
      'wtf.seen.nosey': '{a} ทาย {b} ว่าเป็น {llama}',
      'wtf.known.title': 'เปิดแล้ว (ทั้งวงรู้)',
      'wtf.held.title': 'การ์ดในมือ',
      'wtf.held.play': 'ใช้',
      'wtf.held.passive': 'ทำงานเอง',
      'wtf.check.title': 'เช็คลิสของฉัน',
      'wtf.check.mode.player': 'ชื่อผู้เล่น',
      'wtf.check.mode.color': 'สี (ใส่ชื่อเอง)',
      'wtf.check.hint': 'ติ๊กช่องเพื่อวน: ว่าง → ✓ (มี) → ✗ (ไม่มี)',
      'wtf.color.red': 'แดง',
      'wtf.color.orange': 'ส้ม',
      'wtf.color.yellow': 'เหลือง',
      'wtf.color.green': 'เขียว',
      'wtf.color.mint': 'มิ้นต์',
      'wtf.color.blue': 'ฟ้า',
      'wtf.color.purple': 'ม่วง',
      'wtf.color.pink': 'ชมพู',
      'wtf.color.brown': 'น้ำตาล',
      'wtf.color.gray': 'เทา',
      'wtf.dev.title': '[dev] เสกการ์ด',
      'wtf.dev.hint': 'กดการ์ดเพื่อรันผลทันที (เฉพาะ host เพื่อเทส)',
      'wtf.tag.mute': 'พูดไม่ได้',
      'wtf.fx.broadcast': 'ประกาศ: ใครมี {trait} ต้องเปิด',
      'wtf.fx.missing': 'แอบดูลามะที่ถูกถอด 1 ตัว',
      'wtf.fx.missingNone': 'ไม่มีลามะที่ถูกถอด (เล่นครบ 10 คน)',
      'wtf.fx.spotlight': 'เปิดจุดเด่นตัวเอง 1 ข้อ',
      'wtf.fx.trade': 'แลกดูจุดเด่นกัน',
      'wtf.fx.expose': 'บังคับ {name} เปิดจุดเด่น 1 ข้อ',
      'wtf.fx.crack': 'ทุกคนเปิดจุดเด่นตัวเอง 1 ข้อ',
      'wtf.fx.combo': 'ประกาศ: ใครมีครบทั้งคู่ต้องเปิด',
      'wtf.fx.exclude': 'ใครไม่มี {trait} ยกมือ',
      'wtf.fx.interview': 'ทุกคนตอบเรื่อง {trait}',
      'wtf.fx.peek': 'แอบถามจุดเด่นคนหนึ่ง',
      'wtf.fx.callout': 'ถาม {name} เรื่อง {trait} กลางวง',
      'wtf.fx.scan': 'สแกนดูจุดเด่นคนหนึ่ง',
      'wtf.fx.noseyHold': 'ถือป้าข้างบ้านไว้',
      'wtf.fx.peep': 'แอบดูจุดเด่นคนข้างๆ',
      'wtf.fx.goodneighbor': 'เปิดจุดเด่นให้คนข้างๆ',
      'wtf.fx.verbal': 'คุยกันด้วยปาก (ไม่มีผลอัตโนมัติ)',
      'wtf.fx.bestie': 'กระซิบจุดเด่นให้คนข้างๆ',
      'wtf.fx.truefriend': 'จับมือ {name} ห้ามทายกัน 2 รอบ',
      'wtf.fx.hold': 'เก็บการ์ดขึ้นมือ',
      'wtf.fx.silence': 'สั่งห้าม {name} พูดตานี้',
      'wtf.fx.heavens': 'รอบนี้ห้ามใครทายคนเปิด',
      'wtf.fx.truce': 'รอบนี้ห้ามทายทั้งวง',
      'wtf.fx.manlyroad': 'รอบนี้ทายได้ไม่จำกัด โทษผิดหนักขึ้น',
      'wtf.fx.awaken': '{name} (ที่ออกไปแล้ว) เปิดจุดเด่น 2 ข้อ',
      'wtf.fx.awakenNone': 'ยังไม่มีใครออกจากเกม',
      'wtf.fx.ratio': 'โหวตออกมา {name} ต้องเปิดจุดเด่น',
      'wtf.fx.chairs': 'ทุกคนส่งการ์ดในมือให้คนถัดไป',
      'wtf.fx.vanished': '{name} ใช้หายตัว รอดจากการทาย'
    },
    en: {
      'game.whothefuq.name': 'Who the fuq are you',
      'game.whothefuq.desc': '4–10 players · a llama deduction + bluff game. Everyone holds a secret llama; read the traits and guess others out. The last unguessed llama wins',

      'game.whothefuq.talkSeconds': 'Talk timer',
      'game.whothefuq.talkSeconds.0': 'No timer',
      'game.whothefuq.talkSeconds.60': '1 min',
      'game.whothefuq.talkSeconds.120': '2 min',
      'game.whothefuq.talkSeconds.180': '3 min',
      'game.whothefuq.turnSeconds': 'Turn timer (guess)',
      'game.whothefuq.turnSeconds.0': 'No timer',
      'game.whothefuq.turnSeconds.30': '30s',
      'game.whothefuq.turnSeconds.45': '45s',
      'game.whothefuq.turnSeconds.60': '60s',
      'game.whothefuq.turnSeconds.90': '90s',

      'wtf.phase.announce': 'Announce',
      'wtf.phase.event': 'Fate',
      'wtf.phase.talk': 'Talk',
      'wtf.phase.challenge': 'Who Are You',
      'wtf.phase.over': 'Game over',
      'wtf.roundN': 'Round {n}',
      'wtf.secLeft': '{n}s left',
      'wtf.youOut': 'You are out',
      'wtf.watching': 'Watching',
      'wtf.secretHint': 'Your secret llama — keep it off other screens',
      'wtf.yourTraits': 'Your traits',
      'wtf.advance': 'Next phase',
      'wtf.hostNote': 'The host drives the phases in this scaffold',
      'wtf.youWin': 'You win',
      'wtf.winnerIs': '{name} wins',
      'wtf.again': 'Play again',
      'wtf.lobby': 'Back to room',
      'wtf.sayPh': 'One line about your llama (lying allowed)',
      'wtf.say': 'Announce',
      'wtf.saidAlready': 'You already announced — waiting on others',
      'wtf.announceHelp': 'Everyone says one line about their llama — truth or bluff',
      'wtf.announcedN': 'Announced {n}/{of}',
      'wtf.flip': 'Flip',
      'wtf.waitFlip': 'Waiting for the flipper',
      'wtf.notWired': 'Effect not wired yet',
      'wtf.talkHelp': 'Talk phase: ask, trade info, form alliances, spread lies',
      'wtf.yourHand': 'Cards in hand',
      'wtf.noCards': 'No cards in hand yet',
      'wtf.waitTurn': 'Waiting for {name}',
      'wtf.challengeDone': 'Everyone has acted — waiting for the host',
      'wtf.yourChallenge': 'Your turn — who do you think they are',
      'wtf.doChallenge': 'Who are you',
      'wtf.skip': 'Skip',
      'wtf.players': 'Players',
      'wtf.tag.turn': 'turn',
      'wtf.tag.flip': 'flip',
      'wtf.tag.out': 'out',
      'wtf.infoTable': 'Llama info (10×9)',

      'wtf.log.announced': '{name}: {text}',
      'wtf.log.eventPhase': 'Event phase — round {round}',
      'wtf.log.talkPhase': 'Talk phase',
      'wtf.log.challengePhase': 'Challenge phase',
      'wtf.log.held': '{name} kept a card in hand',
      'wtf.log.flipped': '{name} flipped a card',
      'wtf.log.hit': '{a} guessed {b} right — {b} is out',
      'wtf.log.miss': '{a} guessed {b} wrong',
      'wtf.log.skipped': '{name} skipped',
      'wtf.log.roundEnd': 'End of round {round}',
      'wtf.log.played': '{name} plays {card}',
      'wtf.log.missFree': '{a} guessed {b} wrong (free — no penalty)',
      'wtf.log.guessBackHit': '{a} guessed back {b} right — both out',
      'wtf.log.devFlip': '[dev] conjured {card}',
      'wtf.pending.wait': 'Waiting',
      'wtf.pending.who': 'Waiting for {who}',
      'wtf.confirm': 'Confirm',
      'wtf.prompt.pickOwnTrait': 'Pick one of your own traits to reveal (must be true)',
      'wtf.prompt.pickAnyTrait': 'Pick a trait',
      'wtf.prompt.pickTwo': 'Pick two traits',
      'wtf.prompt.pickTarget': 'Pick a target',
      'wtf.prompt.pickTargetTrait': 'Pick a target and a trait',
      'wtf.prompt.pickNeighbor': 'Pick a neighbor',
      'wtf.prompt.pickOut': 'Pick an eliminated player',
      'wtf.prompt.bestie': 'Pick a neighbor and a trait to tell (lying allowed)',
      'wtf.prompt.vote': 'Vote for one player',
      'wtf.prompt.freeGuess': 'Guess now — pick a player and llama',
      'wtf.prompt.duel': "Guess the other's llama",
      'wtf.prompt.guessBack': 'Guess back — the llama of whoever guessed you',
      'wtf.seen.title': 'What only you know',
      'wtf.seen.missing': 'Removed llama: {llama}',
      'wtf.seen.trait': '{name} has trait: {trait}',
      'wtf.seen.hasYes': '{name} has {trait}',
      'wtf.seen.hasNo': '{name} lacks {trait}',
      'wtf.seen.scan': '{name} has traits: {traits}',
      'wtf.seen.claim': '{name} claims trait: {trait}',
      'wtf.seen.nosey': '{a} guessed {b} as {llama}',
      'wtf.known.title': 'Revealed (public)',
      'wtf.held.title': 'Cards in hand',
      'wtf.held.play': 'Play',
      'wtf.held.passive': 'Auto',
      'wtf.check.title': 'My checklist',
      'wtf.check.mode.player': 'Player names',
      'wtf.check.mode.color': 'Colors (name them)',
      'wtf.check.hint': 'Tap a cell to cycle: blank → ✓ (has) → ✗ (lacks)',
      'wtf.color.red': 'Red',
      'wtf.color.orange': 'Orange',
      'wtf.color.yellow': 'Yellow',
      'wtf.color.green': 'Green',
      'wtf.color.mint': 'Mint',
      'wtf.color.blue': 'Blue',
      'wtf.color.purple': 'Purple',
      'wtf.color.pink': 'Pink',
      'wtf.color.brown': 'Brown',
      'wtf.color.gray': 'Gray',
      'wtf.dev.title': '[dev] Conjure card',
      'wtf.dev.hint': 'Tap a card to run its effect now (host only, for testing)',
      'wtf.tag.mute': 'muted',
      'wtf.fx.broadcast': 'Called out: anyone with {trait} must reveal',
      'wtf.fx.missing': 'Peeked at one removed llama',
      'wtf.fx.missingNone': 'No removed llamas (full 10 players)',
      'wtf.fx.spotlight': 'Revealed one own trait',
      'wtf.fx.trade': 'Traded a trait look',
      'wtf.fx.expose': 'Forced {name} to reveal one trait',
      'wtf.fx.crack': 'Everyone reveals one own trait',
      'wtf.fx.combo': 'Called out: anyone with both must reveal',
      'wtf.fx.exclude': 'Whoever lacks {trait} raises a hand',
      'wtf.fx.interview': 'Everyone answers about {trait}',
      'wtf.fx.peek': 'Secretly asked one player about a trait',
      'wtf.fx.callout': 'Asked {name} about {trait} openly',
      'wtf.fx.scan': 'Scanned one player',
      'wtf.fx.noseyHold': 'Holding Nosey Neighbor',
      'wtf.fx.peep': 'Peeked at a neighbor trait',
      'wtf.fx.goodneighbor': 'Traded a trait with a neighbor',
      'wtf.fx.verbal': 'Talk it out (no automatic effect)',
      'wtf.fx.bestie': 'Whispered a trait to a neighbor',
      'wtf.fx.truefriend': 'Paired with {name} — no challenge for 2 rounds',
      'wtf.fx.hold': 'Kept a card in hand',
      'wtf.fx.silence': 'Silenced {name} this turn',
      'wtf.fx.heavens': 'No one may challenge the flipper this round',
      'wtf.fx.truce': 'No challenges at all this round',
      'wtf.fx.manlyroad': 'Unlimited challenges this round, harsher penalty',
      'wtf.fx.awaken': '{name} (eliminated) reveals two traits',
      'wtf.fx.awakenNone': 'No one is out yet',
      'wtf.fx.ratio': 'The vote lands on {name}, who reveals a trait',
      'wtf.fx.chairs': 'Everyone passes held cards to the next player',
      'wtf.fx.vanished': '{name} vanished — the challenge is cancelled'
    }
  }
});
