/* index.js — ทะเบียนของเกมสลาฟ
   ข้อมูลประจำเกม + ต่อสายไปยังกติกา (game.js) และหน้าจอ (ui.js) */

import { register } from '../../games.js';
import { init, onAction, tick } from './game.js';
import { render } from './ui.js';

register({
  id: 'slave',
  cover: 'assets/game/slave/cover.png',
  table: 'assets/game/slave/table.png',
  minPlayers: 4,
  maxPlayers: 10,

  settings: [
    { key: 'mode',        default: 'normal', options: ['normal', 'endless'] },
    { key: 'turnSeconds', default: 0,        options: [0, 5, 10, 15, 20] }
  ],

  init, onAction, tick, render,

  i18n: {
    th: {
      'game.slave.name': 'สลาฟ',
      'game.slave.desc': '4–10 คน · ทิ้งไพ่ให้หมดก่อนใคร · คนแพ้ต้องยกไพ่ดีที่สุดให้คนชนะรอบหน้า',
      'game.slave.mode': 'โหมด',
      'game.slave.mode.normal': 'ปกติ — สองรอบจบ',
      'game.slave.mode.endless': 'ไม่รู้จบ — มีคะแนน',
      'game.slave.turnSeconds': 'เวลาต่อตา',
      'game.slave.turnSeconds.0': 'ไม่จับเวลา',
      'game.slave.turnSeconds.5': '5 วิ',
      'game.slave.turnSeconds.10': '10 วิ',
      'game.slave.turnSeconds.15': '15 วิ',
      'game.slave.turnSeconds.20': '20 วิ',

      'slave.round': 'รอบ {n}',
      'slave.showBoard': 'ตารางคะแนน',
      'slave.hideBoard': 'ปิดตาราง',
      'slave.scoreboard': 'ตารางคะแนน',
      'slave.emptyPile': 'กองว่าง ลงอะไรก็ได้',
      'slave.playedBy': '{name} ลง',
      'slave.yourTurn': 'ตาคุณ',
      'slave.yourTurnOpening': 'ตาคุณ ต้องลงดอกจิก 3 ด้วย',
      'slave.waitingFor': 'รอ {name}',
      'slave.play': 'ลง',
      'slave.pass': 'ผ่าน',
      'slave.youAreOut': 'คุณหมดไพ่แล้ว รอรอบจบ',
      'slave.passed': 'ผ่าน',
      'slave.toppled': 'โดนล้ม',
      'slave.place': 'ที่ {n}',
      'slave.noticeTopple': '{by} ล้ม {king} — {king} ตกเป็นสลาฟทันที',
      'slave.noticeTimeout': '{name} หมดเวลา ระบบลงให้',
      'slave.noticeTooFew': 'ผู้เล่นเหลือน้อยกว่า 4 คน เกมจบ',
      'slave.pickGive': 'เลือกไพ่ {n} ใบคืนให้ {name}',
      'slave.confirmGive': 'ยืนยัน',
      'slave.youGiveBest': 'คุณต้องยกไพ่ดีที่สุด {n} ใบให้ ระบบเลือกให้เอง',
      'slave.waitExchange': 'รอแลกไพ่ให้ครบทุกคู่',
      'slave.roundOver': 'จบรอบ {n}',
      'slave.gameOver': 'จบเกม',
      'slave.nextRound': 'รอบต่อไป',
      'slave.waitHostNext': 'รอเจ้าของห้องเริ่มรอบต่อไป',
      'slave.voteYes': 'เล่นต่อ',
      'slave.voteNo': 'พอแล้ว',
      'slave.waitVotes': 'รออีก {n} คนโหวต',
      'slave.backToRoom': 'กลับไปที่ห้อง',
      'slave.waitHostRoom': 'รอเจ้าของห้องพากลับไปที่ห้อง',
      'slave.title.king': 'คิง',
      'slave.title.queen': 'ควีน',
      'slave.title.people': 'ประชาชน',
      'slave.title.viceSlave': 'รองสลาฟ',
      'slave.title.slave': 'สลาฟ'
    },
    en: {
      'game.slave.name': 'Slave',
      'game.slave.desc': '4–10 players · shed your hand first · the loser hands their best cards to the winner next round',
      'game.slave.mode': 'Mode',
      'game.slave.mode.normal': 'Normal — two rounds',
      'game.slave.mode.endless': 'Endless — with scoring',
      'game.slave.turnSeconds': 'Turn timer',
      'game.slave.turnSeconds.0': 'No timer',
      'game.slave.turnSeconds.5': '5s',
      'game.slave.turnSeconds.10': '10s',
      'game.slave.turnSeconds.15': '15s',
      'game.slave.turnSeconds.20': '20s',

      'slave.round': 'Round {n}',
      'slave.showBoard': 'Scores',
      'slave.hideBoard': 'Hide scores',
      'slave.scoreboard': 'Scoreboard',
      'slave.emptyPile': 'Empty pile — lead anything',
      'slave.playedBy': 'played by {name}',
      'slave.yourTurn': 'Your turn',
      'slave.yourTurnOpening': 'Your turn — must include 3 of clubs',
      'slave.waitingFor': 'Waiting for {name}',
      'slave.play': 'Play',
      'slave.pass': 'Pass',
      'slave.youAreOut': 'You are out — waiting for the round to end',
      'slave.passed': 'passed',
      'slave.toppled': 'toppled',
      'slave.place': '#{n}',
      'slave.noticeTopple': '{by} toppled {king} — {king} drops to slave',
      'slave.noticeTimeout': '{name} ran out of time — played automatically',
      'slave.noticeTooFew': 'Fewer than 4 players left — game over',
      'slave.pickGive': 'Pick {n} card(s) to give back to {name}',
      'slave.confirmGive': 'Confirm',
      'slave.youGiveBest': 'You must hand over your best {n} card(s) — chosen automatically',
      'slave.waitExchange': 'Waiting for the card swap',
      'slave.roundOver': 'Round {n} over',
      'slave.gameOver': 'Game over',
      'slave.nextRound': 'Next round',
      'slave.waitHostNext': 'Waiting for the host to start the next round',
      'slave.voteYes': 'Keep playing',
      'slave.voteNo': 'Stop here',
      'slave.waitVotes': 'Waiting on {n} vote(s)',
      'slave.backToRoom': 'Back to the room',
      'slave.waitHostRoom': 'Waiting for the host',
      'slave.title.king': 'King',
      'slave.title.queen': 'Queen',
      'slave.title.people': 'People',
      'slave.title.viceSlave': 'Vice slave',
      'slave.title.slave': 'Slave'
    }
  }
});
